steps:
- name: "golang:stretch"
  args: ["ls", "/go"]
- name: "golang:stretch"
  args: ['bash', '-c', 'mkdir -p /go/src/github.com/googlecloudplatform && ln -s $(pwd) /go/src/github.com/googlecloudplatform/kubebuilder && ls /go/src/github.com/googlecloudplatform/kubebuilder && go build github.com/googlecloudplatform/kubebuilder/cmd/kubebuilder']
